desc 'check commands'
long_desc '''
check commands- bunch of sub commands for check manipulation
'''
command :check do |c|
  c.desc 'Modify a check.'
  c.long_desc '''
Specify IDs as comma-separated values, or no IDs to update all.

Check IDS are a combination of the entity name and check name, separated by a colon.

Example: [--ids ENTITY:CHECK,ENTITY:CHECK]

WARNING: There is no way to re-enable a check via the API once it has been disabled! Flapjack will re-enable it when a new event is received for it.
'''
  c.command :update do |update|
    update.desc "Check identifiers (comma-separated, format '<entity_name>:<check_name>')"
    update.arg_name 'ids'
    update.flag [:ids]
    update.desc 'Decommission the check and remove it from the interface and API. Flapjack will re-commission the check if an event is received.'
    update.switch [:disable], :negatable => false
    update.action do |global_options,options,args|
      puts "TODO: check update"
      # Flapjack::Syrup::Check.update(global_options,options,args)
    end
  end
  c.desc 'Get JSON check status data'
  c.long_desc '''
Specify IDs as comma-separated values, or no IDs to get all.

Check IDS are a combination of the entity name and check name, separated by a colon.

Example: [--ids ENTITY:CHECK,ENTITY:CHECK]
'''
  c.command :status do |status|
    status.desc "Check identifiers (comma-separated, format '<entity_name>:<check_name>')"
    status.arg_name 'ids'
    status.flag [:ids]
    status.action do |global_options,options,args|
      puts "TODO: check status"
      # Flapjack::Syrup::Check.status(global_options,options,args)
    end
  end
  c.desc 'Test notifications for a check'
  c.long_desc '''
Send a test notification on the check, in the same way that a real alert would be applied.

Specify IDs as comma-separated values, or no IDs to get all.

Example: [--ids ENTITY:CHECK,ENTITY:CHECK] [--summary "Testing checks"]
'''
  c.command :test do |test|
    test.desc "Check identifiers (comma-separated, format '<entity_name>:<check_name>')"
    test.arg_name 'ids'
    test.flag [:ids]
    test.desc 'Notification text to send'
    test.arg_name 'summary_message'
    test.default_value 'Test generated by flapjack-syrup'
    test.flag [:summary, :s]
    test.action do |global_options,options,args|
      puts "TODO: check test"
      # Flapjack::Syrup::Check.test(global_options,options,args)
    end
  end
end
